import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static bool get isConfigured =>
      android.apiKey.isNotEmpty || ios.apiKey.isNotEmpty || web != null;

  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return null;
    }
  }

  // Optional Web config via --dart-define (useful if not generated by FlutterFire).
  static const String _webApiKey = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
  );
  static const String _webAppId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
  static const String _webMessagingSenderId = String.fromEnvironment(
    'FIREBASE_WEB_MESSAGING_SENDER_ID',
  );
  static const String _webProjectId = String.fromEnvironment(
    'FIREBASE_WEB_PROJECT_ID',
  );
  static const String _webAuthDomain = String.fromEnvironment(
    'FIREBASE_WEB_AUTH_DOMAIN',
  );
  static const String _webStorageBucket = String.fromEnvironment(
    'FIREBASE_WEB_STORAGE_BUCKET',
  );
  static const String _webMeasurementId = String.fromEnvironment(
    'FIREBASE_WEB_MEASUREMENT_ID',
  );

  static FirebaseOptions? get web {
    if (_webApiKey.isEmpty ||
        _webAppId.isEmpty ||
        _webMessagingSenderId.isEmpty ||
        _webProjectId.isEmpty) {
      return null;
    }

    return const FirebaseOptions(
      apiKey: _webApiKey,
      appId: _webAppId,
      messagingSenderId: _webMessagingSenderId,
      projectId: _webProjectId,
      authDomain: _webAuthDomain,
      storageBucket: _webStorageBucket,
      measurementId: _webMeasurementId,
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4AY1N9v9W9coCmnN7jBTbY3bXqMzG2Sw',
    appId: '1:381827995098:android:6ad747c6de5910677b1ce3',
    messagingSenderId: '381827995098',
    projectId: 'irisconsuntivazione',
    storageBucket: 'irisconsuntivazione.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiRrLJdoLsM6J7P2Znwi_B1ej85N6pSGs',
    appId: '1:381827995098:ios:320a001e5eb2f3f17b1ce3',
    messagingSenderId: '381827995098',
    projectId: 'irisconsuntivazione',
    storageBucket: 'irisconsuntivazione.firebasestorage.app',
    iosBundleId: 'com.example.consuntivazioneIris',
  );
}
